apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-test-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/juanjo-vlc/sops-tests.git
    targetRevision: main  # or master, depending on your default branch
    path: encrypted  # Path to encrypted manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: test-sops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
